spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: humanizar-units

  # Configuração de Threads
  threads:
    virtual:
      enabled: true

  # Configurações de OAuth2 Resource Server JWT
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVER_URL}/oauth2/jwks

  # Configurações de datasource
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: humanizar-units-service
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 600000
      minimum-idle: 3
      maximum-pool-size: 10

  # Configurações de Migrations
  sql:
    init:
      mode: always

  # Configurações de JPA com Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[format_sql]": false
    generate-ddl: true
    open-in-view: false

# Configuração do servidor
server:
  port: 9095

# Configuração do Actuator (Health Check)
management:
  health:
      mail:
        enabled: false
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      cache:
        time-to-live: 60s